---
title: "Calles y personas, una placa para Juan Monserrat y Verges"
author: "JJ Merelo"
date: "6 de diciembre de 2017"
output:
  word_document: default
  pdf_document: default
bibliography: biblio.bib
---

# Calles y personas, un homenaje a Juan Monserrat y Vergés

Hay personas que no necesitan calles que lleven su nombre.

Por ejemplo,
el
[ingeniero Ricardo de la Cierva](https://www.change.org/p/ayuntamiento-de-granada-llamar-arquitecto-juan-montserrat-verg%C3%A9s-a-la-calle-ingeniero-ricardo-de-la-cierva). Por
que no existe. Hay ingenieros de la Cierva, hay al menos un Ricardo de
la Cierva. No existe ningún ingeniero Ricardo de la Cierva. 

Este afán por dar calles a lo inexistente no es que sea algo
extraodinario en una ciudad que le concede una a
los
[Niños Luchando](http://granadaimedia.com/calle-ninos-luchando-granada/) o
que
llama
[avenida Circunvalación](http://granada.callejero.net/calle-de-la-circunvalacion-zaidin.html) a
una calle que no sólo no circunvala nada, sino que ni siquiera forma
un arco de círculo medianamente decente. En este último caso se
enmendó el entuerto cambiándole el nombre a Avenida Don Bosco, aunque
en realidad para los vernáculos simplemente se ha añadido "de toda la
vida" al antiguo nombre. Tanto empeño por dar nombres a calles de
conceptos inexistentes deja de lado a otros, mucho más
concretos, aunque por otro lado sirve de acicate para inquirir sobre
lo que no se habla en los carteles de las calles.

En mi caso concreto, esta ausencia es la
de
[Juan Monserrat y Vergés](https://ca.wikipedia.org/wiki/Joan_Montserrat_Verg%C3%A9s),
descrito en la página de la Wikipedia en catalán, la única que existe,
aunque espero que esto cambie en breve, como *arquitecto y masón
catalán*. Hasta hace unos momentos, también figuraba como lugar y
fecha de la muerte "Granada, post 1910". Eso quizás explique la
ausencia del callejero. Mal se puede nombrar una calle tras una
persona que ni siquiera tiene artículo en la Wikipedia en español, y
que aunque lo tuviera, ni siquiera se sabía cuando murió ni, para el
caso, dónde. 

La ausencia de la Universidad de Granada del callejero se explica
porque no es una institución que suela recibir ese tipo de
honores. También porque ahora mismo se extiende por toda la
ciudad. Pero en 1877 residía todavía en el llamado Colegio de San
Pablo, y el rector era, [según la web de la universidad,  D. Santiago López Argüeta](http://www.ugr.es/~archivo/sigloxix.htm), que, 
él sí, tiene una calle en Granada. Fue un rector anterior, Francisco
de Paula Montells y Nadal, quien inició la reforma de tal colegio para
convertirlo en sede de la llamada Universidad Literaria; reforma que
concluyó Juan Montserrat y Vergés en 1879. Fue por tanto la
universidad, como en tantos otros casos, la que trajo a Juan dos años
antes, en 1877, a Granada [@lopez2006intromisiones].

En 1877 Juan contaba con 24 años, pues una vez más según la Wikipedia
en catalán, nació en Reus, provincia de Tarragona en el
año 1853. Estudió en Barcelona, pero por alguna razón, termina los
estudios en 1876 en Madrid, donde hace sus primeras prácticas en el
edificio de la Biblioteca Nacional de España. ¿Comenzó por estas
fechas la vinculación de Juan con Granada? Vamos a unir los
puntos. Francisco Jareño fue el director de esas obras y era a la vez
Académico de la academia de Bellas Artes de San
Fernando. Según
[las actas de la academia](http://www.cervantesvirtual.com/portales/bellas_artes_san_fernando/partes/248345/real-academia-de-bellas-artes-de-san-fernando-comision-de-arquitectura-libros-de-actas-1786-1959-160),
a principios del año 1876 el pintor
granadino
[Eduardo García Guerra](https://es.wikipedia.org/wiki/Eduardo_Garc%C3%ADa_Guerra) solicitó
ser corresponsal de tal academia en Granada. 

>Según la esquela de Juan Montserrat publicada en el Defensor de
>Granada el 11 de agosto de 1909, su mujer se llamaba Agustina
>García, nombre por otro lado totalmente común. 

Sea como fuere, al parecer el joven Juan llamó la atención de Francisco
Jareño que no sólo lo admitió como auxiliar en las obras de la
Biblioteca Nacional, sino que también, posiblemente, le animaría a que
solicitara la beca de arquitectura de la Academia Española en Roma
[@alcalde2004arquitectos]. En el ejercicio teórico que tuvo que
realizar para acceder a la academia tuvo que exponer sobre el sistema
de construcción de la arquitectura romana. Fue el que le tocó en
suerte, pero el hecho de que lo hiciera con tal habilidad que le
proporcionó la beca nos da una pista de cuales pueden ser sus fuentes
de inspiración. 

Posiblemente fuera un poco después de llevar a cabo el examen, en
1877, cuando tuvo que partir para Granada, donde el trabajo se le
acumulaba al joven Juan. No sólo fue llamado a Granada para arreglar el
edificio que iba a albergar a la universidad y de camino traer "pararrayos, teléfonos y
timbres eléctricos" a la misma, según una solicitud de informe que se
hizo el 10 de abril de 1879 a la misma Academia, encargada en aquella
época de autorizar las mismas, sino que también fue nombrado
arquitecto municipal de Granada, arquitecto de las diócesis de Granada
y ya puestos de la de Guadiz Baza. En esta última, al parecer, le
vieron el pelo una sola vez y dimitió un poco más adelante,
posiblemente forzado por los propios prelados. Tampoco le
vieron el pelo salvo en un cuadro en la Academia de Roma y en un
fragmento del arco de Tito, que envió como parte de su pensión. [El cuadro](http://www.elindependientedegranada.es/ciudadania/catalanes-que-hicieron-granada),
pintado por él mismo y su única obra pictórica nos da una idea de su
aspecto: un poblado bigote acorde con la época, entradas ya patentes,
pero una buen amata de pelo; un aspecto serio y pensativo y quizás un
poco triste. Sin duda estaría pensando en esos momentos todas las
responsabilidades que le habían caído encima y si se arrepentiría de
cambiar Roma por Granada.


Porque, además,
por si le quedaba un rato libre a las siete de la tarde de los
domingos, fue arquitecto inspector de Hacienda. Es posible que esto
fuera lo que le pagara el sueldo, porque también consta que un
tribunal de lo contencioso falló a favor de nuestro Juan y en contra
de nuestra universidad por el abono de los honorarios devengados desde
1880 a 1886. Qué sucedió en 1879, nos lo podemos imaginar. Juan acabó
la obra y adiós muy buenas. Pero en esas fechas ya era arquitecto
municipal de Granada. También había dimitido de arquitecto de la
diócesis de Granada. 

No hay muchas calles dedicadas a arquitectos en Granada. Sólo dos, de
hecho. Una de ellas, conocida sobre todo por ser final de [la línea N5
de los autobuses urbanos de Granada](http://www.movilidadgranada.com/bus_linea.php?idioma=es&linea=N5),
está de hecho en una calle no demasiado conocida. Pero menos da una
piedra, piedras que son, precisamente, competencia de los arquitectos
municipales. Decidir qué se hace con ellas, tirarlas y cambiarlas de
sitio. Y esa, precisamente, era una época donde, en Granada, había
un furor por cambiar piedras de sitio. En ["Granada la bella", Ángel
Ganivet aborrece estos cambios](https://es.wikisource.org/wiki/Granada_la_bella:_04)
(cita tomada de [@lopez2006intromisiones])

>A Granada llegó la epidemia del ensanche, y como no había razón para que nos ensancháramos, porque teníamos nuestros ensanches naturales en el barrio de San Lázaro, Albaicín y Camino de Huétor, y más bien nos sobraba población, concebimos la idea famosa de ensancharnos por el centro y el proyecto diabólico de destruir la ciudad, para que el núcleo ideal de ella tuviera que refugiarse en Albaicín. Y con el pretexto de que al Darro se le habían «hinchado alguna vez las narices», acordamos poner sobre él una gran vía. Y la pusimos.

En una muestra más de la *mala follá* granaína, Ángel Ganivet tiene
una calle creada por tal ensanche, tras derribar el barrio de la
Manigua que ocupaba esa zona del centro de Granada. Derribo que no fue
responsabilidad de nuestro Juan,
sino
[Gallego Burín, en los años 40](http://granadablogs.com/terecuerdo/2015/06/16/comienza-el-derribo-de-la-manigua/). Sí
fue responsabilidad suya el derribo
del
[Palacio de Cetti Meriem](http://legadonazari.blogspot.com.es/2016/02/casa-de-los-infantes-o-palacio-de-cetti.html) y
del Arco de las
Orejas,
[este en el año 1884](http://www.ra-bellasartesgranada.es/?cat=17),
situado en la actual plaza de Bibarrambla. Tanto revuelo debió causar
en aquella época tal demolición que le valió a nuestro un *cameo* en la novela "Los
Cármenes de Granada", que se publicó mucho más adelante, en 1927. Esta
novela costumbrista de Armando Palacio Valdés incluye a un personaje,
el tío Perico, que abjura de los cambios que están acabando con el
carácter granadino e increpa a los operarios encargados de la
demolición hasta tal punto que tiene que intervenir "el arquitecto
municipal", nuestro Juan, que se convierte, también, en un personaje
de ficción. 

En esa época, además, andaba en otros menesteres. En 1883 se
constituye la logia Beni Garnata [@mesa1995blas], y Juan aparece como
miembro fundador con el grado uno. Ni esta logia ni ninguna otra de
las que han marcado la historia granadina tienen calle en
Granada. Juan Monserrat usó el
*nick* "Ictinius", que se parece bastante al  [nombre del submarino](https://es.wikipedia.org/wiki/Ict%C3%ADneo_I) que
construyó Narcís Monturiol, un *portmanteau* que combina la idea de
pez y la idea de nave, pero que a la vez representaba la modernidad y
la tecnología y que de hecho fue el nombre que su inventor dio al que
hoy llamamos submarino. Narcís Monturiol también era masón. También
puede suceder que se refiriera
a [Ictinus](https://en.wikipedia.org/wiki/Ictinus), un arquitecto
griego, autor del partenón; así lo dice David Martín Lopez en
[@lopez2007juan]. Siendo esto mucho más plausible, que nuestro Juan
tomase el nombre de un submarino como mote masónico me parece mucho
más poético.

Juan Monserrat se inició en la masonería poco antes del comienzo de la
actividad de la Beni Garnata, en abril de 1883. A partir de ese momento, los *cambios de salario* o ascensos
en la jerarquía masónica tendrían lugar de forma periódica. De hecho, a finales de 1884 ya
había ascendido a segundo vigilante de la logia, y el 1886 ya había
llegado al grado 13. En 1889 y siempre según [@mesa1995blas], aparece
con el grado 24, el cargo de Primer Experto y, ojo al dato, casado. En
algún momento entre 1884 y 1889, ya que en otras actas de la logia
figura como casado, tuvo tiempo de encontrar a una mujer y casarse con
ella. 

En esas fechas, también, tiene lugar el [terremoto de
Andalucía](https://es.wikipedia.org/wiki/Terremoto_de_Andaluc%C3%ADa_de_1884). Murieron más de mil personas, y varios pueblos, sobre todo
en la provincia de Granada, acabaron arrasados y sin una casa en pie,
además en pleno invierno. Tras una fase inicial en que toda España
nos asignó el sambenito de exagerados, hubo un movimiento nacional
para ayudar a los heridos y, sobre todo, reconstruir los
pueblos. Quizás porque [Barcelona fue una de las ciudades que más se
distinguió en la colecta de fondos](http://mcv.revues.org/4102?lang=fr),
quizás porque Juan decidió ofrecer su trabajo de arquitecto de forma
gratuita, recayó en él el diseño de las viviendas que se habrían de
construir en Arenas del Rey, en una localización a quinientos metros
de la anterior. 

## Bibliografía

